name: Deploy to UpCloud Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /var/www/nodemaven-scrape-browser
            
            # Pull latest changes
            git pull origin main
            
            # Install dependencies
            npm install --production
            
            # Restart application with PM2
            pm2 restart nodemaven-scraper
            
            # Save PM2 configuration
            pm2 save
            
            echo "Deployment completed successfully!"
            
      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            pm2 status
            pm2 logs nodemaven-scraper --lines 20 --nostream
